version: '3'       
                   
services:          
  webapp:          
    build: .       
    ports:         
     - "80:80"     
    networks:      
     - counternet  
  redis:           
    image: redis
    networks:      
     - counternet  
networks:          
  counternet:      
    driver: bridge 
